# Generated by Django 5.2.4 on 2025-07-28 15:16

import posts.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen opcional. Tamaño máximo: 5MB. Formatos: JPG, PNG, GIF, WebP', null=True, upload_to='posts/', validators=[posts.models.validate_image_size, posts.models.validate_image_extension]),
        ),
    ]
