# Generated by Django 5.2.4 on 2025-07-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_categoria_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comentario'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Marcar como artículo destacado'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descripción SEO', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='published', max_length=20),
        ),
    ]
