// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 31/7/2025, 06:48:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Skull/Desktop/Proyecto/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Skull/Desktop/Proyecto/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Skull/Desktop/Proyecto/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Skull/Desktop/Proyecto/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Skull/Desktop/Proyecto/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;