# Generated by Django 5.2.4 on 2025-07-29 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created_post', 'Post creado'), ('updated_post', 'Post actualizado'), ('deleted_post', 'Post eliminado'), ('created_user', 'Usuario creado'), ('updated_user', 'Usuario actualizado'), ('deleted_user', 'Usuario eliminado'), ('approved_comment', 'Comentario aprobado'), ('rejected_comment', 'Comentario rechazado'), ('deleted_comment', 'Comentario eliminado'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=100)),
                ('target_model', models.CharField(help_text='Modelo afectado (Post, User, etc.)', max_length=50)),
                ('target_id', models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('description', models.TextField(help_text='Descripción detallada de la acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_posts', models.BooleanField(default=False, help_text='Puede crear, editar y eliminar posts')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Puede gestionar usuarios y permisos')),
                ('can_manage_comments', models.BooleanField(default=False, help_text='Puede moderar comentarios')),
                ('can_view_stats', models.BooleanField(default=True, help_text='Puede ver estadísticas del dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Dashboard',
                'verbose_name_plural': 'Permisos de Dashboard',
            },
        ),
    ]
